### PR TITLE
Fix CM.Disp + enhance autosave timer refresh

### LINKED ISSUE #375: Make 'Seconds till autosave' more precise
#374 adds the functionality of a countdown until the next autosave.
However, sometimes it hangs and does not display the next second (ie., 34, 33, ..., 31).
After some testing, I believe this is due to the CM.Loop not being called in that specific second (in the example the 32st).
Therefore the StatsMenu does not get updated, even though the user might have selected `CM.Config.UpStats` to be 1 second.

For now, I have added the non-optimal feature to the dev-branch to gage user-feedback and collect ideas and possible solutions in this topic.
Even if it is not perfect I still think the current feature serves its purpose, but it would be nice if we could find a way to make it seems less "broken" to the unknowing user.

### PR DESCRIPTION
**Pull request by Chorizorro**
d002cff

Replace calls to `CreateStatsHeader()` by `CM.Disp.CreateStatsHeader()` to fix the stats menu.

8d0accd

Enhance autosave timer by hooking to the Game's drawing method:
- Create a `CM.RegisterHooks()` method to handle hooking to the Game's API;
- Create a `CM.Disp.Draw()` method to handle CM custom draws;
- Implement a timer refresh every 10 frames (0.333 seconds) to avoid skipping seconds in the autosave timer.

I tried not to overthink too much the hooking part, but if we happen to need more hooking in the future, it might be great to do so in another file or find some dedicated methods / objects to do so.
For now, I don't think this is necessary.

This closes #375

### CODE REVIEW

File: CookieMonster.js [hunk 1]
```diff
@@ -3263,8 +3263,10 @@ CM.Disp.AddMenuStats = function(title) {
 		}
 		stats.appendChild(listing('Missed Golden Cookies', document.createTextNode(Beautify(Game.missedGoldenClicks))));
 		if (Game.prefs.autosave) {
-			var timeTillAutosave = Math.min((Game.fps*60 - (Game.T%(Game.fps*60))) / Game.fps, !Game.OnAscend * 60)
-			stats.appendChild(listing('Seconds till autosave', document.createTextNode(Math.floor(timeTillAutosave))));
+			var timer = document.createElement('span');
+			timer.id = 'CMStatsAutosaveTimer';
+			timer.innerText = Game.sayTime(Game.fps * 60 - (Game.OnAscend ? 0 : (Game.T % (Game.fps * 60))), 4);
```
Comment (Chorizorro) [inline CookieMonster.js:3268]: Using the `Game.sayTime` method to format the time instead of displaying raw seconds, both for readability and consistency with some other stats.

File: src/Main.js [hunk 2]
```diff
@@ -242,10 +242,19 @@ CM.DelayInit = function() {
 	if (Game.prefs.popups) Game.Popup('Cookie Monster version ' + CM.VersionMajor + '.' + CM.VersionMinor + ' loaded!');
 	else Game.Notify('Cookie Monster version ' + CM.VersionMajor + '.' + CM.VersionMinor + ' loaded!', '', '', 1, 1);
 
+	CM.RegisterHooks();
```
Comment (DanielNoord) [inline src/Main.js:245]: Really nitpicky, but could you change this to be CM.Main.RegisterHooks()?

File: src/Disp.js [hunk 3]
```diff
@@ -2498,6 +2500,23 @@ CM.Disp.AddMissingUpgrades = function() {
 	}
 }
 
+/**
+ * This function handles custom drawing for the Game.Draw() function.
+ * It is hooked on 'draw' by CM.RegisterHooks()
+ */
+CM.Disp.Draw = function () {
```
Comment (DanielNoord) [inline src/Disp.js:2507]: In the latest revision of CM.Disp I have added a section for `Functions related to display of the full page and initialization of the page`. Perhaps we should rename this to be something like `General functions` and add this function there? I can imagine us adding other things to `CM.Disp.Draw` and then it shouldn't be in the stats page section.

File: src/Main.js (hunk 2 above)
Comment (Chorizorro) [reply src/Main.js:245]: No worries, I'll do it right away!

Comment (Chorizorro) [reply src/Main.js]: Done!

**Comment by DanielNoord** [comment]
Approved! Thanks :)

File: src/Disp.js (hunk 3 above)
Comment (Chorizorro) [reply src/Disp.js]: I've changed the section header to "General functions related to display, drawing and initialization of the page", I thought "General functions" was really to generic (eh) and that adding "drawing" was enough to include the new `CM.Disp.Draw` method. (Feel free to tell me if you prefere another wording)

I've also moved the aforementioned method into the section

**Comment by Chorizorro** [comment]
You're faster in merging my new changes than I'm adding comments xD

File: src/Disp.js (hunk 3 above)
Comment (DanielNoord) [reply src/Disp.js]: Section title is perfect!
Only thing I noticed is that a section called "bottom bar" or something has been removed, so our general section now includes both general as well as bottom bar functions. Probably something I messed up myself while moving the functions around.

To make the document 100% we should move `CM.Disp.Draw` above the bottom bar functions and re-instate a bottom bar section. If you're willing to do that, please go ahead! Otherwise I will do this once I get back to my computer. 
_(I approved this merge since it does fix the issue and I felt that this little reorganization deserves its own pull request)_

Comment (Chorizorro) [reply src/Disp.js]: You're right, I didn't notice that!
This is fixed by #420 (both moving the method and restoring the bottom bar section comment)
