### PR TITLE
Fix Lucky/Chain cookies stats when CpS is zero

### LINKED ISSUE #156: NaN when cookies per second == 0
immagine

### LINKED ISSUE #267: Cursed Finger changes the requirements and MAX rewards for Lucky/Chain to Infinity
0 CpS, fresh save. Requirements are 0 and MAX rewards are 13 and 7/6 respectively, as they should be.
image

With Cursed Finger active. Requirements and MAX rewards change to Infinity.
image

### PR DESCRIPTION
**Pull request by Chorizorro**
Set Lucky/Chain cookies requirements to 0 if CPS buff multiplier is 0 to avoid a division by zero resulting in NaN / Infinity being displayed.

This closes #156 and closes #267

### CODE REVIEW

File: CookieMonster.js [hunk 1]
```diff
@@ -4164,8 +4174,7 @@ CM.Sim.SellBuildingsForChoEgg = function() {
 	// Get money made by selling all remaining buildings
 	for (var i in CM.Sim.Objects) {
 		var me = CM.Sim.Objects[i];
-		debug = CM.Sim.BuildingSell(Game.Objects[me.name], Game.Objects[i].basePrice, me.amount, Game.Objects[i].free, me.amount);
-		sellTotal += debug;
+		sellTotal += CM.Sim.BuildingSell(Game.Objects[me.name], Game.Objects[i].basePrice, me.amount, Game.Objects[i].free, me.amount);
```
Comment (Chorizorro) [inline CookieMonster.js:4177]: Ugh, this should have been in #355 (last minute fix in the sources but I forgot to regenerate the CookieMonster.js), sorry.

Don't know the best way to deal with that, though?

**Comment by DanielNoord** [comment]
No worries, as this is only a minor commit I will keep it in this pull request.
