### PR TITLE
Fix building price displayed in sell mode

### LINKED ISSUE #359: Check CM.Disp.Tooltip for legacy code
**I've noticed that this isn't actually doing anything**, as `Beautify(Game.Objects[name].getPrice())` is never matched in the string; maybe this is some legacy code to remove?

_Originally posted by @Chorizorro in https://github.com/Aktanusa/CookieMonster/pull/355#discussion_r531712864_

### PR DESCRIPTION
**Pull request by Chorizorro**
This fix changes the building price displayed in both object tooltip and in the store.

To do so, it adds an optional parameter `noSim` to `CM.Sim.BuildingSell` to allow for building price calculation while taking the current Game multipliers instead of the CM.Sim ones. Basically, it acts as a reversed version of the old `emuAura` removed in #355 .

This closes #359

### CODE REVIEW

File: CookieMonster.js [hunk 1]
```diff
@@ -1424,7 +1424,17 @@ CM.Disp.UpdateBuildings = function() {
...
+			l('productPrice' + o.id).style.color = '';
+			/*
+			 * Fix sell price displayed in the object in the store.
+			 *
+			 * The buildings sell price displayed by the game itself (without any mod) is incorrect.
+			 * The following line of code fixes this issue, and can be safely removed when the game gets fixed.
+			 * 
+			 * This issue is extensively detailed here: https://github.com/Aktanusa/CookieMonster/issues/359#issuecomment-735658262
+			 */
+			l('productPrice' + o.id).innerHTML = Beautify(CM.Sim.BuildingSell(o, o.basePrice, o.amount, o.free, Game.buyBulk, 1));
```
Comment (Chorizorro) [inline CookieMonster.js:1437]: I've added this to fix the price displayed in store so that it's consistent with the one displayed in the tooltip, but I'm not sure if this is a good thing (for example, could it mess with other plugins?)

File: CookieMonster.js [hunk 2]
```diff
@@ -3658,12 +3671,16 @@ CM.Sim.BuildingSell = function(build, basePrice, start, free, amount) {
 	return Math.ceil(price);*/
 
 	// Calculate money gains from selling buildings
+	// If noSim is set, use Game methods to compute price instead of Sim ones.
+	noSim = typeof noSim === "undefined" ? 0 : noSim;
 	var moni = 0;
+	if (amount == -1) amount = start;
+	if (!amount) amount = Game.buyBulk;
```
Comment (Chorizorro) [inline CookieMonster.js:3678]: I've added this to be consistent with the `Game.Object.sell` method. It allows to use the -1 value for "sell all", as it is used in `Game.buyBulk`
