### PR TITLE
Fix buildings value in chocolate egg calculation

### LINKED ISSUE #347: Dragon Auras are not computed correctly
While working on #305 , I noticed a strange behaviour on Chocolate Egg Cookies value, leading to incorrect simulated value.

This is most likely caused by the "Reality bending" Krumblor aura not being handled properly while simulating building selling in `CM.Sim.BuildingSell`.

I think I'll be able to look a bit further into this issue in the next days.

---

<details><summary><strong>Test save for import (click to expand)</strong></summary>
Mi4wMzF8fDE2MDQ0OTQ4MzM0MDU7MTU5OTE2NTg3MDY1ODsxNjA2MzEwMTU2MDA1O0Nob3Jpem9ycm8gdGVzdDtjZ2xxaXwwMTExMTAwMTAxMDEwMDEwMDEwMTB8MS4xMjIxMDg0MzczNjA1NzU2ZSs1MzsyLjk2NTM4ODg0ODY3MDQ0OWUrNTM7MjI0NzU7MTI4NzE7MS44NTcxNjYwMjE1NzY3MzQ0ZSs1Mzs2NTU1OzA7MDsyLjU5MzQzNTkwNTc0NzA3NzdlKzUxOzA7MTswOzA7LTE7MTAyOzQwNTQ7OC40MTU4NDI4ODMwODY1MDRlKzQ4OzExNzsxNDsyMDstMTs0OzswOzA7MTM3MzkxMDcwMTkxNzI7MTE1NTIyNTY4MzEwODA7MjE4Njg1MDE4ODA5MjswOzA7MDsxOzI7Mzs0OzI1OzE7MjswOzUwOzA7MDs2OzE1MTsxNjA2MjM4NjI5NDUyOzA7MTsxMjksMjI3OzQxOzE7MTs3LjgwNTk0MTQwMTg3NTg4NmUrNDQ7fDgzMCwxNDgxLDYuODgxOTY0MTI4MjY5NDY1ZSs0OSw3LCwwLDgzMDs4MTAsMTE2MCw2LjEwODI5MDE4Njk2MzIyZSs0OSwxLCwwLDgxMDs3NTAsMTEwMCwyLjM3NzY5NzMxNjUyMjU5OTRlKzQ2LDEwLDE2MDYzMTAyMTU5NTQ6MjoxNjA2MzEwNzE0MjYyOjA6OTA2OjMxMTk6MTo0OjE2MDQ0OTQ4MzM0MTg6IDExMTExMDEwMDExMTExMDAwMDEwMDAwMTEwMDAwMDAwMDAgMzoxOjA6MDozOjA6MDowOjM6MDowOjA6MzoxOjA6MDozOjA6MDowOjM6MDowOjA6MzoxOjM6MDozOjA6MDowOjM6MDowOjA6MzoxOjA6MDozOjA6MDowOjM6MDowOjA6MzowOjA6MDozOjA6MDowOjM6MDowOjA6MzowOjA6MDozOjA6MDowOjM6MDowOjA6LDAsNzUwOzc1MCwxMTAwLDEuOTQ4MTcxMzI4NDc5OTg4ZSs0OCwwLCwxLDc1MDs3MjAsMTA3MCwyLjUyMTYyMDEwNTg4MzgxMzhlKzQ3LDAsLDEsNzIwOzcxMCwxMDYwLDUuNDM4ODc0NjgxOTU1ODNlKzQ2LDEsMjoyODoxOjk4MTc4Ny4zNTAwOTUwNzA0OjA6IDI0MzA6NTo4NDo1MDowOjA6MiE2MDc6MjotMjg6NTI3OjA6MDoyITg2MDoyOi0zNjoxMDA6MDowOjIhMzg0MDo1OjIwOjU0OjA6MDoyITY4NDE6MTo1NDo3MjowOjA6MiE2MTEzOjA6MTY6MTc2OjA6MDoyITQ1NTM6MjotNDE6NDU1OjA6MDoyITgxMDk6NTo2NzoxNjA6MDowOjIhOTkxNjoxOjE2OjMyNzowOjA6MiE5Njk1OjA6LTEyOjU3MjowOjA6MiExMTMxOTo1OjI6MjM0OjA6MDoyITI1MTU6NDotMTkyOjM2MzowOjA6MiE1MTMzOjQ6LTIyNDo2Mjg6MDowOjIhMTIxMDU6MjotNDE6MTI5OjA6MDoyITE1MDU4OjA6LTEwOjc5NzowOjA6MiExNDQyOTo1Oi0yODo0OTU6MDowOjAhIDEsMCw3MTA7NzAwLDEwNTAsMi40NTA1MDMyMDQxNjQ3ODI0ZSs0NywxLDEwLzgvNiAzIDE2MDQ5MjAwMzk1NTIgMSwwLDcwMDs2ODAsMTY3MCw3LjE2Nzg1NTAxNzE0MzE5OGUrNDYsMTAsMTEzIDIwOCAxMTI0IDEsMCw2ODA7NjQwLDk5MCwxLjkwODYwNDgzMDY4MjM1OGUrNDYsMCwsMSw2NDA7NjMwLDk4MSwxLjAwODEyMDEzNzY2MjM4OTZlKzQ3LDEsLDEsNjMwOzY0MCw5OTAsMS41MTI2MTE2NDM3MDIzNTMyZSs0OSwxLCwxLDY0MDs2MDAsOTUwLDMuNDA3Mzc0NDI0MDk1ODM2ZSs0OCwwLCwxLDYwMDs2MDAsOTUwLDMuMzc4MzYzNTc3NzU4NzAxZSs0OSwwLCwxLDYwMDs1ODAsOTMwLDEuOTQ0MDIwMDI1NTQ0ODU1N2UrNTAsMCwsMSw1ODA7NTYwLDkxMCw0LjYwNTY3MjI4NzY5NjU1NWUrNTAsMCwsMSw1NjA7NTYwLDkxMCwzLjEzNDY4MjQ5OTg0MDIzM2UrNTEsMCwsMSw1NjA7NTEwLDg2MCw2LjIxMjQ3ODA5MTI5NjY5MWUrNTAsMCwsMSw1MTA7NDkwLDg0NiwyLjQ5MzA2ODE2MDUyMTU5NmUrNTEsMSwsMSw0OTA7fDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDExMTExMTExMDAxMTExMTEwMDExMTAxMTAwMTExMTExMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDEwMTAxMDAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAxMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDExMTExMTExMTExMTExMTExMTEwMTAxMDAwMDAwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMDAwMDAwMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDExMTExMTExMDAwMDAwMDAxMTExMTExMXwxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTExMTEwMDAwMDAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMDExMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAxMDAwMDEwMDAwMDAxMTEwMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTEwMTExMTEwMTAxMTExMDAwMDAxMDExMDAwMDExMTExMTExMTExMTExMTExMDAxMTExMTExMTExMTExMDAwMDExMTExMTExMTEwMDAxMTEwMTExMTAwMDAwMDAwfHw%3D%21END%21
</details>

**Context + how to reproduce**

To keep the testing as simple as possible, this save doesn't have wrinklers / stock market goods.

The 2 initial auras are not relevant for chocolate egg computation (Dragon Cursor and Breath of Milk).
Here is a simple summary of the chocolate egg simulated value upon aura switch :

| Action | Earth Shatterer | Reality Bending | Sim chocolate egg | Real chocolate egg
| ------------- | ------------- | ------------- | ------------- | ------------- |
| _Initial_ | No  | No | 7.693 Sexdec | 7.793 Sexdec |
| Switch 1 aura to Earth Shatterer from _Initial_ | Yes  | No | 7.693 Sexdec | 7.793 Sexdec |
| Switch 1 aura to Reality Bending from _Initial_ | No | Yes | 7.689 Sexdec | 7.793 Sexdec |
| Switch both auras to Earth Shatterer + Reality Bending from _Initial_ | Yes | Yes | 7.793 Sexdec | 7.793 Sexdec |

The last simulation is the only one correct.
Both initial and switch to ES have the same computed value, whereas switch to RB has a lower value (probably because of the building sold to switch auras).

### PR DESCRIPTION
**Pull request by Chorizorro**
Fix the calculated buildings value in chocolate egg by adding a sim version of `modifyBuildingPrice` method, allowing for proper simulation of the cookies earned by selling all buildings under the best dragon auras (Earth Shatterer + Reality Bending).

# Approach

The method `CM.Cache.RemakeSellForChoEgg` calculating the chocolate egg value `CM.Cache.SellForChoEgg` calls the method `CM.Sim.BuildingSell` to get the cokies earned when a building is sold. However, this method `CM.Sim.BuildingSell` had 2 problems leading to the calculated value being incorrect:
- it wasn't properly simulating the Reality Bending aura, only Earth Shatterer;
- it was based on the `Game.modifyBuildingPrice` method to calculate buildings value, which includes a multiplier that depends on an aura (Fierce Hoarder), leading to a difference between expected auras and calculated ones.

## Changes in the chocolate egg calculation method

To fix this, I've moved the code computing building selling values to a dedicated simulation method `CM.Sim.SellBuildingsForChoEgg` which creates a simulation that:
1. Changes the aura to Earth Shatterer + Reality Bending if necessary (and sacrifices the required buildings);
2. Calculates the cookies earned for selling all the remaining buildings.

## Other methods added for the simulation

To get the good simulated values instead of the current Game ones, I've added these methods:
- `CM.Sim.getSellMultiplier` based on `Game.object.getSellMultiplier`;
- `CM.Sim.modifyBuildingPrice` base on `Game.modifyBuildingPrice`.

---

This closes #347

### CODE REVIEW

File: src/Cache.js [hunk 1]
```diff
@@ -313,6 +277,8 @@ CM.Cache.RemakeSellForChoEgg = function() {
 		}
 		sellTotal += goodsVal * Game.cookiesPsRawHighest;
 	}
+	// Compute cookies earned by selling all buildings with optimal auras (ES + RB)
+	sellTotal += CM.Sim.SellBuildingsForChoEgg();
```
Comment (Chorizorro) [inline src/Cache.js:281]: I've moved the buildings selling value after the stock market selling to be consistent with the way you do it for real (as you can't sell all your stock market goods if you don't have any banks)

File: src/Disp.js [hunk 2]
```diff
@@ -1996,10 +1996,10 @@ CM.Disp.Tooltip = function(type, name) {
 		}
 		else if (Game.buyMode == -1) {
 			if (Game.buyBulk == -1) {
-				l('tooltip').innerHTML = l('tooltip').innerHTML.split(Beautify(Game.Objects[name].getPrice())).join('-' + Beautify(CM.Sim.BuildingSell(Game.Objects[name], Game.Objects[name].basePrice, Game.Objects[name].amount, Game.Objects[name].free, Game.Objects[name].amount, 0)));
+				l('tooltip').innerHTML = l('tooltip').innerHTML.split(Beautify(Game.Objects[name].getPrice())).join('-' + Beautify(CM.Sim.BuildingSell(Game.Objects[name], Game.Objects[name].basePrice, Game.Objects[name].amount, Game.Objects[name].free, Game.Objects[name].amount)));
 			}
 			else {
-				l('tooltip').innerHTML = l('tooltip').innerHTML.split(Beautify(Game.Objects[name].getPrice())).join('-' + Beautify(CM.Sim.BuildingSell(Game.Objects[name], Game.Objects[name].basePrice, Game.Objects[name].amount, Game.Objects[name].free, Game.buyBulk, 0)));
+				l('tooltip').innerHTML = l('tooltip').innerHTML.split(Beautify(Game.Objects[name].getPrice())).join('-' + Beautify(CM.Sim.BuildingSell(Game.Objects[name], Game.Objects[name].basePrice, Game.Objects[name].amount, Game.Objects[name].free, Game.buyBulk)));
 			}
```
Comment (Chorizorro) [inline src/Disp.js:2003]: The `CM.Sim.BuildingSell` method signature has been changed, leading to these modifications.
It's the only place where the `CM.Sim.BuildingSell` is called other than the chocolate egg calculation one.

**I've noticed that this isn't actually doing anything**, as `Beautify(Game.Objects[name].getPrice())` is never matched in the string; maybe this is some legacy code to remove?

File: src/Sim.js [hunk 3]
```diff
@@ -620,3 +615,76 @@ CM.Sim.ResetBonus = function(possiblePresMax) {
...
+
+	// CM.Sim.CalculateGains();
+
+	// CM.Sim.CheckOtherAchiev();
+
+	// if (lastAchievementsOwned != CM.Sim.AchievementsOwned) {
+	// 	CM.Sim.CalculateGains();
+	// }
+
+	// CM.Cache.DoRemakeBuildPrices = 1;
```
Comment (Chorizorro) [inline src/Sim.js:687]: I'm unsure of what to do at the end of the simulation. I don't think calculating gains and achievements is necessary as we're not interested in getting the CPS gain unlike in other simulation methods, but I would like a confirmation for this.

**Comment by DanielNoord** [comment]
Seems correct! Merging :)

File: src/Disp.js (hunk 2 above)
Comment (Aktanusa) [reply src/Disp.js:2003]: I'll repeat what I wrote in Issue #359 :

It's the return string of the function that is being matched. This is still needed.

Notice that Beautify(Game.Objects[name].getPrice()) is not in quotes. You won't find it in the source CC. It's a dynamic string.

It is to change the value of the tooltip to my calculated value.  If I'm misunderstanding you, please correct me.

File: src/Sim.js (hunk 3 above)
Comment (Aktanusa) [reply src/Sim.js:687]: Hmm, it's been a while.  I'll take a quite look.

Comment (Chorizorro) [reply src/Sim.js:687]: Ok, thank you for taking the time to check this! 🙂
